//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.Library.Models.SqlModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWException
    {
        public int ID { get; set; }
        public System.DateTimeOffset Timestamp { get; set; }
        public string Table { get; set; }
        public string Function { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionMsg { get; set; }
        public string StackTrace { get; set; }
        public Nullable<int> HttpStatusCode { get; set; }
        public string ServiceRequestID { get; set; }
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public string LastResultXml { get; set; }
        public Nullable<System.DateTimeOffset> RequestStartTime { get; set; }
        public string RequestResults { get; set; }
    }
}
