//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.Library.Models.SqlModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouriteTopic
    {
        public int Id { get; set; }
        public string Userid { get; set; }
        public int TopicID { get; set; }
        public int UnreadMsgCount { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
