//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.Library.Models.SqlModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricDataSet
    {
        public MetricDataSet()
        {
            this.Chart_DataSet = new HashSet<Chart_DataSet>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string GroupID { get; set; }
        public string Creater { get; set; }
        public int RecordCount { get; set; }
        public string Category { get; set; }
        public string Counter { get; set; }
        public string Instance { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Chart_DataSet> Chart_DataSet { get; set; }
    }
}
