//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.Library.Models.SqlModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSGorillaEntities : DbContext
    {
        public MSGorillaEntities()
            : base("name=MSGorillaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FavouriteTopic> FavouriteTopics { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<MetricDataSet> MetricDataSets { get; set; }
        public virtual DbSet<NotificationCount> NotificationCounts { get; set; }
        public virtual DbSet<Schema> Schemata { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Chart_DataSet> Chart_DataSet { get; set; }
        public virtual DbSet<MetricChart> MetricCharts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
    }
}
