//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.Library.Models.SqlModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCount
    {
        public string Userid { get; set; }
        public int UnreadHomelineMsgCount { get; set; }
        public int UnreadOwnerlineMsgCount { get; set; }
        public int UnreadAtlineMsgCount { get; set; }
        public int UnreadReplyCount { get; set; }
        public int UnreadImportantMsgCount { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
