//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.Library.Models.SqlModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.FavouriteTopics = new HashSet<FavouriteTopic>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MsgCount { get; set; }
        public string GroupID { get; set; }
    
        public virtual ICollection<FavouriteTopic> FavouriteTopics { get; set; }
        public virtual Group Group { get; set; }
    }
}
