//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.StatusReporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryData
    {
        public System.DateTime Date { get; set; }
        public int UserCount { get; set; }
        public int RobotCount { get; set; }
        public int TopicCount { get; set; }
        public int CountOfMsgPostedByRobot { get; set; }
    }
}
