//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.MailStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailMessage
    {
        public long ID { get; set; }
        public int MailboxID { get; set; }
        public int Uid { get; set; }
        public int SequenceNumber { get; set; }
        public string MSGorillaMessageID { get; set; }
        public bool Recent { get; set; }
        public bool Seen { get; set; }
        public int Important { get; set; }
        public System.DateTimeOffset Timestamp { get; set; }
        public int Size { get; set; }
        public bool Deleted { get; set; }
    
        public virtual MailBox MailBox { get; set; }
    }
}
