//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSGorilla.MailStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailBox
    {
        public MailBox()
        {
            this.MailMessages = new HashSet<MailMessage>();
        }
    
        public int MailboxID { get; set; }
        public string Userid { get; set; }
        public string Path { get; set; }
        public int Exist { get; set; }
        public int Recent { get; set; }
        public int UidValidity { get; set; }
        public int UidNext { get; set; }
    
        public virtual ICollection<MailMessage> MailMessages { get; set; }
    }
}
