// <auto-generated />
namespace MSGorilla.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_important_msg_count : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_important_msg_count));
        
        string IMigrationMetadata.Id
        {
            get { return "201407030519350_add_important_msg_count"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
